[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#00ff00"  # Matrix neon green
backgroundColor = "#000000"  # Black background
secondaryBackgroundColor = "#0a0a0a"  # Slightly lighter black
textColor = "#00ff00"  # Matrix neon green text
font = "monospace"  # Terminal-like font
